# Generated by Django 3.2.16 on 2023-02-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_recipie_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Time_minutes',
            new_name='time_minutes',
        ),
    ]
